/* Built-in dataset (best-effort snapshot, as of 2026-05-04).
   Rates change often and many are tiered / promo-based. Always verify with the product’s official page.
*/

// eslint-disable-next-line no-unused-vars
window.DATA_AS_OF = "2026-05-04";

// eslint-disable-next-line no-unused-vars
window.DEFAULT_RATES = [
  // --- High-yield / digital-first savings ---
  {
    id: "maribank_savings_0_1m",
    bank: "MariBank (formerly SeaBank PH)",
    product: "Savings (₱0–₱1,000,000 tier)",
    ratePa: 3.25,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.maribank.ph/fees-rates",
    notes: "Tiered: 3.25% p.a. applies to balances ₱0–₱1,000,000. Interest credited daily; subject to 20% tax.",
  },
  {
    id: "maribank_savings_over_1m",
    bank: "MariBank (formerly SeaBank PH)",
    product: "Savings (above ₱1,000,000 tier)",
    ratePa: 3.75,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.maribank.ph/fees-rates",
    notes:
      "Tiered: 3.75% p.a. applies only to the portion above ₱1,000,000. Interest credited daily; subject to 20% tax.",
  },
  {
    id: "gotyme_go_save",
    bank: "GoTyme Bank",
    product: "Go Save",
    ratePa: 3.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.gotyme.com.ph/help/go-save/understanding-go-save/computing-your-go-save-interest-rate",
    notes: "GoTyme Help Center: 3% interest annually; paid monthly; subject to 20% withholding tax.",
  },
  {
    id: "komo_savings",
    bank: "Komo (EastWest Rural Bank)",
    product: "Komo Savings",
    ratePa: 2.5,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.komo.ph/savings",
    notes: "Advertised starting at 2.5% p.a. with daily tracking; credited monthly.",
  },
  {
    id: "netbank_mobile_savings",
    bank: "Netbank Mobile (rural bank)",
    product: "Regular Savings (new accounts)",
    ratePa: 3.25,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://netbank.ph/netbank-mobile-faqs/",
    notes: "Netbank FAQ lists 3.25% p.a. for new accounts; daily crediting/compounding; subject to change.",
  },
  {
    id: "diskartech_adb_up_to_50k",
    bank: "RCBC DiskarTech",
    product: "Savings (ADB up to ₱50,000)",
    ratePa: 4.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://diskartech.ph/faqs/",
    notes: "4% p.a. on Average Daily Balance up to ₱50,000 (per DiskarTech FAQs).",
  },
  {
    id: "diskartech_over_50k",
    bank: "RCBC DiskarTech",
    product: "Savings (ADB above ₱50,000.01 to ₱2,000,000)",
    ratePa: 1.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://diskartech.ph/faqs/",
    notes: "1% p.a. tier mentioned for balances above ₱50,000.01 up to ₱2,000,000 (per DiskarTech FAQs).",
  },
  {
    id: "uno_savings_below_5k",
    bank: "UNO Digital Bank",
    product: "Savings (below ₱5,000)",
    ratePa: 3.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.uno.bank/savings-account/",
    notes: "UNO advertises 3.0% p.a. below ₱5,000; interest credited daily.",
  },
  {
    id: "uno_savings_5k_up",
    bank: "UNO Digital Bank",
    product: "Savings (₱5,000 and up)",
    ratePa: 3.5,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.uno.bank/savings-account/",
    notes: "UNO advertises up to 3.50% p.a. for ₱5,000+; interest credited daily.",
  },
  {
    id: "maya_savings_base",
    bank: "Maya Bank",
    product: "Maya Savings (base)",
    ratePa: 3.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.mayabank.ph/10percentboost/",
    notes:
      "Maya promo page shows 3.5% p.a. and states base becomes 3% p.a. starting April 1, 2026. Verify current base/boost mechanics in-app.",
  },

  // Tonik (savings + stashes)
  {
    id: "tonik_account_savings",
    bank: "Tonik Digital Bank",
    product: "Tonik Account (transactional savings)",
    ratePa: 1.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://tonikbank.com/themes/tonikbankv1/images/annual-reports/TDB-2024-Annual-Report.pdf",
    notes: "Tonik 2024 Annual Report describes Tonik Account with 1% savings rate p.a. Verify in-app for latest.",
  },
  {
    id: "tonik_solo_stash",
    bank: "Tonik Digital Bank",
    product: "Stash (Solo)",
    ratePa: 4.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://tonikbank.com/themes/tonikbankv1/images/annual-reports/TDB-2024-Annual-Report.pdf",
    notes: "Tonik 2024 Annual Report: Stash has higher interest rate of 4% p.a. Verify in-app for latest.",
  },
  {
    id: "tonik_group_stash_base",
    bank: "Tonik Digital Bank",
    product: "Group Stash (base)",
    ratePa: 4.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://tonikbank.com/themes/tonikbankv1/images/annual-reports/TDB-2024-Annual-Report.pdf",
    notes:
      "Tonik 2024 Annual Report: Group Stash rate 4.0%–4.5% p.a. depending on unlocking higher rate; verify in-app for rules.",
  },
  {
    id: "tonik_group_stash_unlocked",
    bank: "Tonik Digital Bank",
    product: "Group Stash (unlocked / max)",
    ratePa: 4.5,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://tonikbank.com/themes/tonikbankv1/images/annual-reports/TDB-2024-Annual-Report.pdf",
    notes:
      "Tonik 2024 Annual Report: Group Stash can reach 4.5% p.a. when higher rate is unlocked; verify in-app for rules.",
  },

  // --- Time deposits (PH) ---
  {
    id: "tonik_td_6mo_2026",
    category: "time_deposit",
    bank: "Tonik Digital Bank",
    product: "Time Deposit (6 months)",
    ratePa: 6.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://philstartech.com/news/2026/02/15/16982/digital-bank-tonik-upgrades-time-deposit-interest-rates/",
    notes: "Reported upgrade: 6% (6 months), gross p.a.; subject to 20% withholding tax on interest.",
  },
  {
    id: "tonik_td_9mo_2026",
    category: "time_deposit",
    bank: "Tonik Digital Bank",
    product: "Time Deposit (9 months)",
    ratePa: 7.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://philstartech.com/news/2026/02/15/16982/digital-bank-tonik-upgrades-time-deposit-interest-rates/",
    notes: "Reported upgrade: 7% (9 months), gross p.a.; subject to 20% withholding tax on interest.",
  },
  {
    id: "tonik_td_12mo_2026",
    category: "time_deposit",
    bank: "Tonik Digital Bank",
    product: "Time Deposit (12 months)",
    ratePa: 8.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://philstartech.com/news/2026/02/15/16982/digital-bank-tonik-upgrades-time-deposit-interest-rates/",
    notes: "Reported upgrade: 8% (12 months), gross p.a.; subject to 20% withholding tax on interest.",
  },
  {
    id: "tonik_td_18mo_2026",
    category: "time_deposit",
    bank: "Tonik Digital Bank",
    product: "Time Deposit (18 months)",
    ratePa: 6.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://philstartech.com/news/2026/02/15/16982/digital-bank-tonik-upgrades-time-deposit-interest-rates/",
    notes: "Reported: 6% (18 months), gross p.a.; subject to 20% withholding tax on interest.",
  },
  {
    id: "tonik_td_24mo_2026",
    category: "time_deposit",
    bank: "Tonik Digital Bank",
    product: "Time Deposit (24 months)",
    ratePa: 6.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://philstartech.com/news/2026/02/15/16982/digital-bank-tonik-upgrades-time-deposit-interest-rates/",
    notes: "Reported: 6% (24 months), gross p.a.; subject to 20% withholding tax on interest.",
  },

  // --- E-wallet marketplace savings (GCash GSave partners) ---
  {
    id: "gcash_gsave_cimb",
    bank: "GCash (GSave by CIMB)",
    product: "GSave by CIMB (base)",
    ratePa: 2.6,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://help.gcash.com/hc/en-us/articles/4414721290521-What-are-the-GSave-Interest-Rates-and-Transaction-Limits",
    notes: "GCash Help Center lists 2.60% p.a. base rate; credited monthly; subject to 20% tax.",
  },
  {
    id: "gcash_gsave_bpi_mysaveup",
    bank: "GCash (GSave #MySaveUp by BPI)",
    product: "#MySaveUp by BPI (via GSave)",
    ratePa: 0.0925,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://help.gcash.com/hc/en-us/articles/4414721290521-What-are-the-GSave-Interest-Rates-and-Transaction-Limits",
    notes: "GCash Help Center lists 0.0925% p.a. base rate.",
  },
  {
    id: "gcash_gsave_maybank_ezysaveplus",
    bank: "GCash (GSave EzySave+ by Maybank)",
    product: "EzySave+ by Maybank (via GSave)",
    ratePa: 0.35,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://help.gcash.com/hc/en-us/articles/4414721290521-What-are-the-GSave-Interest-Rates-and-Transaction-Limits",
    notes: "GCash Help Center lists 0.35% p.a. base rate.",
  },
  {
    id: "gcash_gsave_uno_ready_max",
    bank: "GCash (GSave #UNOReady by UNO)",
    product: "#UNOReady (max tier, via GSave)",
    ratePa: 3.5,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://help.gcash.com/hc/en-us/articles/4414721290521-What-are-the-GSave-Interest-Rates-and-Transaction-Limits",
    notes: "GCash Help Center lists up to 3.50% p.a.; tiered by end-of-day balance.",
  },
  {
    id: "gcash_gsave_cebuana_ec_savings",
    bank: "GCash (GSave eC-Savings by Cebuana Lhuillier Rural Bank)",
    product: "eC-Savings (via GSave)",
    ratePa: 3.0,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://help.gcash.com/hc/en-us/articles/43849045104409-What-is-the-interest-rate-for-eC-Savings-by-Cebuana-Lhuillier-Rural-Bank",
    notes: "GCash Help Center lists 3.0% p.a. base rate.",
  },

  // --- Time deposits (PH) ---
  {
    id: "cimb_maxsave_td_3m_regular_2026",
    category: "time_deposit",
    bank: "CIMB Bank PH",
    product: "MaxSave Time Deposit (3 months, Regular)",
    ratePa: 4.25,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl:
      "https://www.cimbbank.com.ph/en/help-and-support/customer-advisories/2026/advisory-on-maxsave-time-deposit-interest-rates.html",
    notes:
      "Official advisory: rates effective Jan 9, 2026. Tenors available as of Apr 14, 2026: 3, 6, 12 months (24-month removed for new placements).",
  },
  {
    id: "cimb_maxsave_td_6m_regular_2026",
    category: "time_deposit",
    bank: "CIMB Bank PH",
    product: "MaxSave Time Deposit (6 months, Regular)",
    ratePa: 4.25,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl:
      "https://www.cimbbank.com.ph/en/help-and-support/customer-advisories/2026/advisory-on-maxsave-time-deposit-interest-rates.html",
    notes:
      "Official advisory: rates effective Jan 9, 2026. Tenors available as of Apr 14, 2026: 3, 6, 12 months (24-month removed for new placements).",
  },
  {
    id: "cimb_maxsave_td_12m_regular_2026",
    category: "time_deposit",
    bank: "CIMB Bank PH",
    product: "MaxSave Time Deposit (12 months, Regular)",
    ratePa: 4.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl:
      "https://www.cimbbank.com.ph/en/help-and-support/customer-advisories/2026/advisory-on-maxsave-time-deposit-interest-rates.html",
    notes:
      "Official advisory: rates effective Jan 9, 2026. Tenors available as of Apr 14, 2026: 3, 6, 12 months (24-month removed for new placements).",
  },
  {
    id: "cimb_maxsave_td_3m_prime_2026",
    category: "time_deposit",
    bank: "CIMB Bank PH",
    product: "MaxSave Time Deposit (3 months, CIMB Prime/Biz)",
    ratePa: 4.75,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl:
      "https://www.cimbbank.com.ph/en/help-and-support/customer-advisories/2026/advisory-on-maxsave-time-deposit-interest-rates.html",
    notes:
      "Official advisory: rates effective Jan 9, 2026. Tenors available as of Apr 14, 2026: 3, 6, 12 months (24-month removed for new placements).",
  },
  {
    id: "cimb_maxsave_td_6m_prime_2026",
    category: "time_deposit",
    bank: "CIMB Bank PH",
    product: "MaxSave Time Deposit (6 months, CIMB Prime/Biz)",
    ratePa: 5.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl:
      "https://www.cimbbank.com.ph/en/help-and-support/customer-advisories/2026/advisory-on-maxsave-time-deposit-interest-rates.html",
    notes:
      "Official advisory: rates effective Jan 9, 2026. Tenors available as of Apr 14, 2026: 3, 6, 12 months (24-month removed for new placements).",
  },
  {
    id: "cimb_maxsave_td_12m_prime_2026",
    category: "time_deposit",
    bank: "CIMB Bank PH",
    product: "MaxSave Time Deposit (12 months, CIMB Prime/Biz)",
    ratePa: 4.25,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl:
      "https://www.cimbbank.com.ph/en/help-and-support/customer-advisories/2026/advisory-on-maxsave-time-deposit-interest-rates.html",
    notes:
      "Official advisory: rates effective Jan 9, 2026. Tenors available as of Apr 14, 2026: 3, 6, 12 months (24-month removed for new placements).",
  },
  {
    id: "netbank_td_6m",
    category: "time_deposit",
    bank: "Netbank Mobile (rural bank)",
    product: "Time Deposit (6 months)",
    ratePa: 4.5,
    minDepositPhp: 10000,
    updated: "2026-05-04",
    sourceUrl: "https://netbank.ph/netbank-mobile/",
    notes: "Netbank lists TD offerings effective Apr 8, 2025: 6 months at 4.5% p.a.",
  },
  {
    id: "netbank_td_12m",
    category: "time_deposit",
    bank: "Netbank Mobile (rural bank)",
    product: "Time Deposit (12 months)",
    ratePa: 5.0,
    minDepositPhp: 10000,
    updated: "2026-05-04",
    sourceUrl: "https://netbank.ph/netbank-mobile/",
    notes: "Netbank lists TD offerings effective Apr 8, 2025: 12 months at 5% p.a.",
  },
  {
    id: "uno_unoboost_td_3_5m",
    category: "time_deposit",
    bank: "UNO Digital Bank",
    product: "#UNOboost Time Deposit (3–5 months)",
    ratePa: 4.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://www.uno.bank/time-deposit/",
    notes: "UNO page: #UNOboost rates by term. This row is 4.00% for 3–5 months.",
  },
  {
    id: "uno_unoboost_td_6_9m",
    category: "time_deposit",
    bank: "UNO Digital Bank",
    product: "#UNOboost Time Deposit (6–9 months)",
    ratePa: 4.25,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://www.uno.bank/time-deposit/",
    notes: "UNO page: #UNOboost rates by term. This row is 4.25% for 6–9 months.",
  },
  {
    id: "uno_unoboost_td_10_11m",
    category: "time_deposit",
    bank: "UNO Digital Bank",
    product: "#UNOboost Time Deposit (10–11 months)",
    ratePa: 4.5,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://www.uno.bank/time-deposit/",
    notes: "UNO page: #UNOboost rates by term. This row is 4.50% for 10–11 months.",
  },
  {
    id: "uno_unoboost_td_12m",
    category: "time_deposit",
    bank: "UNO Digital Bank",
    product: "#UNOboost Time Deposit (12 months)",
    ratePa: 5.5,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://www.uno.bank/time-deposit/",
    notes: "UNO page: #UNOboost is 5.50% gross p.a. for 12 months.",
  },
  {
    id: "uno_unoearn_td_12m",
    category: "time_deposit",
    bank: "UNO Digital Bank",
    product: "#UNOearn Time Deposit (12 months, monthly payouts)",
    ratePa: 4.75,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://www.uno.bank/time-deposit/",
    notes: "UNO page: #UNOearn is 4.75% gross p.a. for 12 months (monthly payouts).",
  },
  {
    id: "uno_unoearn_td_24m",
    category: "time_deposit",
    bank: "UNO Digital Bank",
    product: "#UNOearn Time Deposit (24 months, monthly payouts)",
    ratePa: 5.0,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://www.uno.bank/time-deposit/",
    notes: "UNO page: #UNOearn is 5.00% gross p.a. for 24 months (monthly payouts).",
  },

  // Traditional banks that publish time deposit rate tables online (rates are usually indicative)
  {
    id: "metrobank_online_td_10k_199k_30_364d",
    category: "time_deposit",
    bank: "Metrobank",
    product: "Online Time Deposit (₱10k–₱199,999 · 30–364 days)",
    ratePa: 4.125,
    minDepositPhp: 10000,
    updated: "2026-05-04",
    sourceUrl: "https://www.metrobank.com.ph/articles/time-deposit-rates-and-fees",
    notes:
      "Metrobank published Online Time Deposit table (effective April 2026). Rates can change; confirm inside Metrobank Online/App.",
  },
  {
    id: "metrobank_online_td_200k_9_999_999_30_364d",
    category: "time_deposit",
    bank: "Metrobank",
    product: "Online Time Deposit (₱200k–₱9,999,999 · 30–364 days)",
    ratePa: 4.25,
    minDepositPhp: 200000,
    updated: "2026-05-04",
    sourceUrl: "https://www.metrobank.com.ph/articles/time-deposit-rates-and-fees",
    notes:
      "Metrobank published Online Time Deposit table (effective April 2026). Rates can change; confirm inside Metrobank Online/App.",
  },
  {
    id: "metrobank_online_td_10m_up_30_364d",
    category: "time_deposit",
    bank: "Metrobank",
    product: "Online Time Deposit (₱10,000,000+ · 30–364 days)",
    ratePa: 4.5,
    minDepositPhp: 10000000,
    updated: "2026-05-04",
    sourceUrl: "https://www.metrobank.com.ph/articles/time-deposit-rates-and-fees",
    notes:
      "Metrobank published Online Time Deposit table (effective April 2026). Rates can change; confirm inside Metrobank Online/App.",
  },
  {
    id: "bdo_peso_td_1k_100k_30_360d",
    category: "time_deposit",
    bank: "BDO Unibank",
    product: "Peso Time Deposit (₱1k–<₱100k · 30–360 days)",
    ratePa: 0.125,
    minDepositPhp: 1000,
    updated: "2026-05-04",
    sourceUrl: "https://www.bdo.com.ph/personal/accounts/time-deposit/peso-time-deposit",
    notes: "BDO page lists indicative rates per annum; confirm with branch upon placement.",
  },
  {
    id: "bdo_peso_td_100k_200k_180_360d",
    category: "time_deposit",
    bank: "BDO Unibank",
    product: "Peso Time Deposit (₱100k–<₱200k · 180–360 days)",
    ratePa: 0.25,
    minDepositPhp: 100000,
    updated: "2026-05-04",
    sourceUrl: "https://www.bdo.com.ph/personal/accounts/time-deposit/peso-time-deposit",
    notes: "BDO page lists indicative rates per annum; confirm with branch upon placement.",
  },
  {
    id: "securitybank_td_12m_100k_299k",
    category: "time_deposit",
    bank: "Security Bank",
    product: "Peso Time Deposit (12 months · ₱100k–₱299,999)",
    ratePa: 2.1,
    minDepositPhp: 100000,
    updated: "2026-05-04",
    sourceUrl: "https://www.securitybank.com/personal/accounts/time-deposit/time-deposit-rates/",
    notes: "Security Bank publishes indicative TD tables by amount/tenor; subject to change without notice.",
  },
  {
    id: "securitybank_td_12m_5m_up",
    category: "time_deposit",
    bank: "Security Bank",
    product: "Peso Time Deposit (12 months · ₱5,000,000+)",
    ratePa: 2.5,
    minDepositPhp: 5000000,
    updated: "2026-05-04",
    sourceUrl: "https://www.securitybank.com/personal/accounts/time-deposit/time-deposit-rates/",
    notes: "Security Bank publishes indicative TD tables by amount/tenor; subject to change without notice.",
  },

  // --- Traditional bank savings (examples with published rates) ---
  {
    id: "bdo_atm_savings",
    bank: "BDO Unibank",
    product: "ATM Savings",
    ratePa: 0.0625,
    minDepositPhp: 2000,
    updated: "2026-05-04",
    sourceUrl: "https://www.bdo.com.ph/personal/accounts/savings/peso-savings/atm-savings",
    notes: "BDO page lists 0.0625% gross interest rate per annum (peso ATM savings).",
  },
  {
    id: "bpi_mysaveup",
    bank: "BPI",
    product: "#MySaveUp",
    ratePa: 0.0925,
    minDepositPhp: 1,
    updated: "2026-05-04",
    sourceUrl: "https://www.bpi.com.ph/personal/bank/deposits/deposit-rates-savings-and-checking",
    notes: "BPI deposit rates page lists 0.0925% p.a. (required daily balance to earn interest applies).",
  },
  {
    id: "bpi_jumpstart",
    bank: "BPI",
    product: "Jumpstart Savings",
    ratePa: 0.0625,
    minDepositPhp: 100,
    updated: "2026-05-04",
    sourceUrl: "https://www.bpi.com.ph/personal/bank/deposits/deposit-rates-savings-and-checking",
    notes: "BPI deposit rates page lists 0.0625% p.a.",
  },
  {
    id: "bpi_maxi_saver",
    bank: "BPI",
    product: "Maxi-Saver",
    ratePa: 0.125,
    minDepositPhp: 2000000,
    updated: "2026-05-04",
    sourceUrl: "https://www.bpi.com.ph/personal/bank/deposits/deposit-rates-savings-and-checking",
    notes: "BPI deposit rates page lists 0.125% p.a. (with potential bonus depending on withdrawals).",
  },
  {
    id: "bpi_saver_plus",
    bank: "BPI",
    product: "Saver-Plus",
    ratePa: 0.0625,
    minDepositPhp: 3000,
    updated: "2026-05-04",
    sourceUrl: "https://www.bpi.com.ph/personal/bank/deposits/deposit-rates-savings-and-checking",
    notes: "BPI deposit rates page lists 0.0625% p.a. (requires higher balance to earn interest).",
  },
  {
    id: "metrobank_savings",
    bank: "Metrobank",
    product: "Savings accounts (headline)",
    ratePa: 0.0625,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.metrobank.com.ph/personal/accounts/savings",
    notes: "Metrobank page states 0.0625% interest rate for savings accounts (verify per account type).",
  },
  {
    id: "eastwest_regular_savings",
    bank: "EastWest Bank",
    product: "Regular Savings",
    ratePa: 0.1,
    minDepositPhp: 5000,
    updated: "2026-05-04",
    sourceUrl: "https://www.eastwestbanker.com/rates",
    notes: "EastWest rates page lists 0.100% p.a. for Regular Savings.",
  },
  {
    id: "aub_starter_savings",
    bank: "Asia United Bank (AUB)",
    product: "Starter Savings",
    ratePa: 0.1,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.aub.com.ph/deposit/savings",
    notes: "AUB page lists 0.100% p.a. for Starter Savings.",
  },
  {
    id: "rcbc_digital_savings",
    bank: "RCBC",
    product: "Digital Savings Account (Pulz)",
    ratePa: 0.15,
    minDepositPhp: 100,
    updated: "2026-05-04",
    sourceUrl: "https://www.rcbc.com/digitalsavingsaccount",
    notes: "RCBC page lists 0.15% interest rate; balance to earn interest applies.",
  },
  {
    id: "rcbc_isave_5k_100k",
    bank: "RCBC",
    product: "iSave (₱5,000–<₱100,000 tier)",
    ratePa: 0.15,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.rcbc.com/isave",
    notes: "Tiered virtual savings: 0.150% p.a. for ₱5,000 to <₱100,000.",
  },
  {
    id: "rcbc_isave_100k_500k",
    bank: "RCBC",
    product: "iSave (₱100,000–<₱500,000 tier)",
    ratePa: 0.175,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.rcbc.com/isave",
    notes: "Tiered virtual savings: 0.175% p.a. for ₱100,000 to <₱500,000.",
  },
  {
    id: "rcbc_isave_500k_up",
    bank: "RCBC",
    product: "iSave (₱500,000+ tier)",
    ratePa: 0.2,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://www.rcbc.com/isave",
    notes: "Tiered virtual savings: 0.200% p.a. for ₱500,000 and above.",
  },
  {
    id: "ofbank_debit_savings",
    bank: "OFBank (digital-only gov bank)",
    product: "Visa/Regular Debit Card Savings",
    ratePa: 0.05,
    minDepositPhp: 0,
    updated: "2026-05-04",
    sourceUrl: "https://ofbank.com.ph/products-services/deposits/ofbank-visa-debit-card",
    notes: "OFBank product page lists 0.05% interest rate (per annum).",
  },
];
